//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahou.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mahou.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to convert specific last word count by pressing hotkey and then 1-9 on keyboard..
        /// </summary>
        internal static string AllowToConvertSpecificLastWord {
            get {
                return ResourceManager.GetString("AllowToConvertSpecificLastWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ****Attention****.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart with Windows.
        /// </summary>
        internal static string AutostartWithWindows {
            get {
                return ResourceManager.GetString("AutostartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block CTRL.
        /// </summary>
        internal static string BlockCTRL {
            get {
                return ResourceManager.GetString("BlockCTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks hotkeys that use Control,
        ///when &quot;Switch layout by key&quot; is set to Left/Right Control..
        /// </summary>
        internal static string BlocksHotkeysThatUseControl {
            get {
                return ResourceManager.GetString("BlocksHotkeysThatUseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates, and update if needed..
        /// </summary>
        internal static string CheckForUpdatesAndUpdateIfNeeded {
            get {
                return ResourceManager.GetString("CheckForUpdatesAndUpdateIfNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled Mahou will check for updates at startup..
        /// </summary>
        internal static string CheckForUpdatesTooltip {
            get {
                return ResourceManager.GetString("CheckForUpdatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors:.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors and font of small tip.(Left - foreground, Right - background).
        /// </summary>
        internal static string ColorsAndFontOfSmallTipLeftForegroundRightBackground {
            get {
                return ResourceManager.GetString("ColorsAndFontOfSmallTipLeftForegroundRightBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combines some abilities of Convert selection with enabled CS-Switch and when it disabled.(Enable CS-Switch for it to work)
        ///It can:
        ///1.Conversion from multiple languages at once.
        ///2.Ignore symbols feature work in it.
        ///3.Auto get language of text(not all symbols(the ones that exist in both layouts) can be rightly recognized if wrong layout selected from begin)
        ///4.Ability to convert symbols that exist in both layouts different if change layout before conversion..
        /// </summary>
        internal static string CombinesSomeAbilities {
            get {
                return ResourceManager.GetString("CombinesSomeAbilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Pause(by Default) to convert last inputted word.
        ///Press Scroll(by Default) while selected text is focused to convert it.
        ///Press Shift+Pause(by Default) to convert last inputted line.
        ///Press Ctrl+Alt+Shift+Insert to show Mahou main window.
        ///Press Ctrl+Alt+Shift+F12 to shutdown Mahou.
        ///
        ///*Note that if you typing in not of selected in settings layouts(locales/languages), conversion will switch typed text to Language 1(Ignored if Cycle Mode is ON).
        ///
        ///**If you have problems with symbols conversion(selecti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonToolTop {
            get {
                return ResourceManager.GetString("CommonToolTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert line.
        /// </summary>
        internal static string ConvertLine {
            get {
                return ResourceManager.GetString("ConvertLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert multiple words hotkey:.
        /// </summary>
        internal static string ConvertMultipleWordsHotkey {
            get {
                return ResourceManager.GetString("ConvertMultipleWordsHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert selection.
        /// </summary>
        internal static string ConvertSelection {
            get {
                return ResourceManager.GetString("ConvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert word.
        /// </summary>
        internal static string ConvertWord {
            get {
                return ResourceManager.GetString("ConvertWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option enabled, Covert selection will use layout switching.
        ///All characters will be rewriten as they must.(no problems with symbols
        ///There also an CS-Switch+ in More Configs page 2..
        /// </summary>
        internal static string CovertSelectionUseLayoutSwitching {
            get {
                return ResourceManager.GetString("CovertSelectionUseLayoutSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS-Switch.
        /// </summary>
        internal static string CSSwitch {
            get {
                return ResourceManager.GetString("CSSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Mode.
        /// </summary>
        internal static string CycleMode {
            get {
                return ResourceManager.GetString("CycleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option enabled, Cycle Mode will use Emulation of Alt+Shift/Win+Space instead &quot;sending window message&quot; that changes layout..
        /// </summary>
        internal static string CycleModeWillUseEmulationOf {
            get {
                return ResourceManager.GetString("CycleModeWillUseEmulationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay:.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed ONLY to search for errors, logs are saved in Mahou&apos;s folder, in folder Logs..
        /// </summary>
        internal static string DesignedONLYToSearchForErrors {
            get {
                return ResourceManager.GetString("DesignedONLYToSearchForErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language:.
        /// </summary>
        internal static string DisplayLanguage {
            get {
                return ResourceManager.GetString("DisplayLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language tooltip only on layout change.
        ///Time of displaying is 7x[Refresh rate]..
        /// </summary>
        internal static string DisplayLanguageTooltip {
            get {
                return ResourceManager.GetString("DisplayLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double hotkey:.
        /// </summary>
        internal static string DoubleHotkey {
            get {
                return ResourceManager.GetString("DoubleHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emu.
        /// </summary>
        internal static string Emu {
            get {
                return ResourceManager.GetString("Emu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emu Type.
        /// </summary>
        internal static string EmuType {
            get {
                return ResourceManager.GetString("EmuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable check for updates at startup..
        /// </summary>
        internal static string EnableCheckForUpdatesAtStartup {
            get {
                return ResourceManager.GetString("EnableCheckForUpdatesAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging for debugging..
        /// </summary>
        internal static string EnableLoggingForDebugging {
            get {
                return ResourceManager.GetString("EnableLoggingForDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables double hotkey ability,
        ///and makes it possible to set modifies to hotkey..
        /// </summary>
        internal static string EnablesDoubleHotkeyAbility {
            get {
                return ResourceManager.GetString("EnablesDoubleHotkeyAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables more tries to get selected text in Convert selection..
        /// </summary>
        internal static string EnablesMoreTriesToGetSelectedTextInConvertSelection {
            get {
                return ResourceManager.GetString("EnablesMoreTriesToGetSelectedTextInConvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling this will disable LCtrl/RCtrl from &quot;Switch layout by key&quot;.
        ///While this enabled pressing LCtrl/RCtrl will switch to specified layout..
        /// </summary>
        internal static string EnablingThisWillDisable {
            get {
                return ResourceManager.GetString("EnablingThisWillDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling this, will reselect text after &quot;Convert selection&quot;..
        /// </summary>
        internal static string EnablingThisWillReselectText {
            get {
                return ResourceManager.GetString("EnablingThisWillReselectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during check....
        /// </summary>
        internal static string ErrorOccuredDuringCheck {
            get {
                return ResourceManager.GetString("ErrorOccuredDuringCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental CS-Switch+.
        /// </summary>
        internal static string ExperimentalCSSwitch {
            get {
                return ResourceManager.GetString("ExperimentalCSSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get Update info, can&apos;t connent to &apos;github.com&apos;, check your internet connection or proxy configuration..
        /// </summary>
        internal static string FailedToGetUpdate {
            get {
                return ResourceManager.GetString("FailedToGetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to GitHub repository to view source or report issue..
        /// </summary>
        internal static string GoToGitHubRepositoryToViewSourceOrReportIssue {
            get {
                return ResourceManager.GetString("GoToGitHubRepositoryToViewSourceOrReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Scroll Lock when active language 1, selected in main window..
        /// </summary>
        internal static string HighlightScrollLock {
            get {
                return ResourceManager.GetString("HighlightScrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight ScrollLock when language 1 is active..
        /// </summary>
        internal static string HighlightScrollLockWhenLanguage1IsActive {
            get {
                return ResourceManager.GetString("HighlightScrollLockWhenLanguage1IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is current hotkey for &quot;Convert line&quot;.
        ///Press any key to assign it, or key with modifiers(ALT,CTRL,SHIFT).
        /// </summary>
        internal static string HotkeyForConvertLinePress {
            get {
                return ResourceManager.GetString("HotkeyForConvertLinePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is current hotkey for &quot;Convert selection&quot;.
        ///Press any key to assign it, or key with modifiers(ALT,CTRL,SHIFT)..
        /// </summary>
        internal static string HotkeyForConvertSelectionPress {
            get {
                return ResourceManager.GetString("HotkeyForConvertSelectionPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is current hotkey for &quot;Convert word&quot;.
        ///Press any key to assign it, or key with modifiers(ALT,CTRL,SHIFT)..
        /// </summary>
        internal static string HotkeyForConvertWordPress {
            get {
                return ResourceManager.GetString("HotkeyForConvertWordPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        internal static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey with CapsLock warning!.
        /// </summary>
        internal static string HotkeyWithCapsLockWarning {
            get {
                return ResourceManager.GetString("HotkeyWithCapsLockWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCtrl switches to:.
        /// </summary>
        internal static string LCtrlSwitchesTo {
            get {
                return ResourceManager.GetString("LCtrlSwitchesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging disabled due to 10+ logging errors, last error:.
        /// </summary>
        internal static string LoggingDisabled {
            get {
                return ResourceManager.GetString("LoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahou (魔法) A magical layout switcher..
        /// </summary>
        internal static string MahouAMagicalLayoutSwitcher {
            get {
                return ResourceManager.GetString("MahouAMagicalLayoutSwitcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahou snippets error!.
        /// </summary>
        internal static string MahouSnippetsError {
            get {
                return ResourceManager.GetString("MahouSnippetsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahou successfully updated!.
        /// </summary>
        internal static string MahouSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("MahouSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahou update.
        /// </summary>
        internal static string MahouUpdate {
            get {
                return ResourceManager.GetString("MahouUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes background of language tooltip transparent.
        ///Don&apos;t forget to change text color.(because &quot;White&quot; is default)
        ///Some fonts may look bad, try changing to another.(&quot;Georgia&quot; or &quot;Palatino Linotype&quot; is recommend).
        /// </summary>
        internal static string MakesBackgroundOfLanguage {
            get {
                return ResourceManager.GetString("MakesBackgroundOfLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, modifiers will be repressed after conversion.
        ///Due to new hotkey managment modifiers NEVER stuck(recommenden)..
        /// </summary>
        internal static string ModifiersWillBeRepressed {
            get {
                return ResourceManager.GetString("ModifiersWillBeRepressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More configs.
        /// </summary>
        internal static string MoreConfigs {
            get {
                return ResourceManager.GetString("MoreConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Tries:.
        /// </summary>
        internal static string MoreTries {
            get {
                return ResourceManager.GetString("MoreTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, mouse cursor hovers text it will display a small tip of what langauge is now using..
        /// </summary>
        internal static string MouseCursorHoversTextItWillDisplayASmallTipOfWhatLangaugeIsNowUsing {
            get {
                return ResourceManager.GetString("MouseCursorHoversTextItWillDisplayASmallTipOfWhatLangaugeIsNowUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name/Password.
        /// </summary>
        internal static string NamePassword {
            get {
                return ResourceManager.GetString("NamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On change.
        /// </summary>
        internal static string OnChange {
            get {
                return ResourceManager.GetString("OnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only works when Cycle Mode is OFF..
        /// </summary>
        internal static string OnlyWorksWhenCycleModeIsOFF {
            get {
                return ResourceManager.GetString("OnlyWorksWhenCycleModeIsOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position relative to mouse position..
        /// </summary>
        internal static string PositionRelativeToMousePosition {
            get {
                return ResourceManager.GetString("PositionRelativeToMousePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have pressed just modifiers for Convert selection hotkey!!.
        /// </summary>
        internal static string PressedModifiersForConvertSelectionHotkey {
            get {
                return ResourceManager.GetString("PressedModifiersForConvertSelectionHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have pressed just modifiers for Convert word hotkey!!.
        /// </summary>
        internal static string PressedModifiersForConvertWordHotkey {
            get {
                return ResourceManager.GetString("PressedModifiersForConvertWordHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing LCtrl will switch layout to selected..
        /// </summary>
        internal static string PressingLCtrlWillSwitchLayout {
            get {
                return ResourceManager.GetString("PressingLCtrlWillSwitchLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, pressing ONE space AFTER word will not clear last word..
        /// </summary>
        internal static string PressingONESpace {
            get {
                return ResourceManager.GetString("PressingONESpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing RCtrl will switch layout to selected..
        /// </summary>
        internal static string PressingRCtrlWillSwitchLayout {
            get {
                return ResourceManager.GetString("PressingRCtrlWillSwitchLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this enabled, pressing Space will expand small (which starts with &quot;-&gt;&quot;) word, to big (which is between &quot;====&gt;&quot; and &quot;&lt;====&quot;) word/text fragment..
        /// </summary>
        internal static string PressingSpace {
            get {
                return ResourceManager.GetString("PressingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCtrl switches to:.
        /// </summary>
        internal static string RCtrlSwitchesTo {
            get {
                return ResourceManager.GetString("RCtrlSwitchesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh rate(ms):.
        /// </summary>
        internal static string RefreshRatems {
            get {
                return ResourceManager.GetString("RefreshRatems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Press.
        /// </summary>
        internal static string RePress {
            get {
                return ResourceManager.GetString("RePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Select.
        /// </summary>
        internal static string ReSelect {
            get {
                return ResourceManager.GetString("ReSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type for Emulate change layout.
        ///Win+Space works only in Windows 10!!
        ///Win+Space also will work better in Metro apps..
        /// </summary>
        internal static string SelectTypeForEmulateChangeLayout {
            get {
                return ResourceManager.GetString("SelectTypeForEmulateChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:port.
        /// </summary>
        internal static string Serverport {
            get {
                return ResourceManager.GetString("Serverport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide.
        /// </summary>
        internal static string ShowHide {
            get {
                return ResourceManager.GetString("ShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of language tooltip..
        /// </summary>
        internal static string SizeOfLanguageTooltip {
            get {
                return ResourceManager.GetString("SizeOfLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets configured wrong....
        /// </summary>
        internal static string SnippetsConfiguredWrong {
            get {
                return ResourceManager.GetString("SnippetsConfiguredWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed of checking cursor type.(if it equals &quot;I&quot; ).
        /// </summary>
        internal static string SpeedOfCheckingCursorTypeifItEqualsI {
            get {
                return ResourceManager.GetString("SpeedOfCheckingCursorTypeifItEqualsI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between layouts.
        /// </summary>
        internal static string SwitchBetweenLayouts {
            get {
                return ResourceManager.GetString("SwitchBetweenLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching layout depends on &quot;Cycle Mode&quot; and &quot;Emu&quot; options.
        /// </summary>
        internal static string SwitchingLayoutDependsOnCycleModeEmuOptions {
            get {
                return ResourceManager.GetString("SwitchingLayoutDependsOnCycleModeEmuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch layout by key:.
        /// </summary>
        internal static string SwitchLayoutByKey {
            get {
                return ResourceManager.GetString("SwitchLayoutByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Ignore:.
        /// </summary>
        internal static string SymbolIgnore {
            get {
                return ResourceManager.GetString("SymbolIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, symbols []{};&apos;:&quot;,./&lt;&gt;&quot;? will be ignored and will not be converted.
        ///Works in Convert word, Convert line, Convert selection with Cylce Mode and CS-Switch enabled.
        ///Won&apos;t work if you have &gt;2 layouts an Cycle Mode enabled!.
        /// </summary>
        internal static string SymbolsWillBeIgnored {
            get {
                return ResourceManager.GetString("SymbolsWillBeIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out....
        /// </summary>
        internal static string TimedOut {
            get {
                return ResourceManager.GetString("TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to wait second hotkey press(ms).
        /// </summary>
        internal static string TimeToWaitSecondHotkeyPressms {
            get {
                return ResourceManager.GetString("TimeToWaitSecondHotkeyPressms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles visibility of icon in a tray.
        ///If it is hidden, to show configs window hit CTRL+ALT+SHIFT+INSERT or just run Mahou.exe again..
        /// </summary>
        internal static string TogglesVisibilityOfIconInATray {
            get {
                return ResourceManager.GetString("TogglesVisibilityOfIconInATray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent background in language tooltip.
        /// </summary>
        internal static string TransparentBackgroundInLanguageTooltip {
            get {
                return ResourceManager.GetString("TransparentBackgroundInLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon.
        /// </summary>
        internal static string TrayIcon {
            get {
                return ResourceManager.GetString("TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update complete!.
        /// </summary>
        internal static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mahou to.
        /// </summary>
        internal static string UpdateMahouTo {
            get {
                return ResourceManager.GetString("UpdateMahouTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use snippets.
        /// </summary>
        internal static string UseSnippets {
            get {
                return ResourceManager.GetString("UseSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use specific layout changing by Left/Right CTRLS.
        /// </summary>
        internal static string UseSpecificLayoutChangingByLeftRightCTRLS {
            get {
                return ResourceManager.GetString("UseSpecificLayoutChangingByLeftRightCTRLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using CapsLock with CapsLock assigned as [Switch Only Key] will produce issues, disable [Switch Only Key] feature or assign it to another key..
        /// </summary>
        internal static string UsingCapsLockProduceIssues {
            get {
                return ResourceManager.GetString("UsingCapsLockProduceIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on Github.
        /// </summary>
        internal static string ViewOnGithub {
            get {
                return ResourceManager.GetString("ViewOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While this option enabled, [Convert word] and [Convert line] and [Convert selection with &quot;CS-Switch&quot; enabled]
        ///will just cycle between all locales instead of switching between selected in settings.
        ///This mode works for almost all programs.
        ///If there is program in which [Convert word] or [Convert line] or [Convert selection with &quot;CS-Switch&quot; enabled] not work,
        ///try with this option enabled.
        ///If you have just 2 layouts(input languages) it is HIGHLY RECOMMENDED to turn it ON, and &quot;Emu&quot; too to ON..
        /// </summary>
        internal static string WhileThisOptionEnabled {
            get {
                return ResourceManager.GetString("WhileThisOptionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have assigned same hotkeys for Convert word &amp; Convert line, that is impossible!!.
        /// </summary>
        internal static string YouHaveAssignedSameHotkeys {
            get {
                return ResourceManager.GetString("YouHaveAssignedSameHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have latest version..
        /// </summary>
        internal static string YouHaveLatestVersion {
            get {
                return ResourceManager.GetString("YouHaveLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have pressed just modifiers for Convert line hotkey!!.
        /// </summary>
        internal static string YouHavePressedJustModifiersForConvertLineHotkey {
            get {
                return ResourceManager.GetString("YouHavePressedJustModifiersForConvertLineHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have removed selected locales, reselect..
        /// </summary>
        internal static string YouHaveRemovedSelectedLocalesReselect {
            get {
                return ResourceManager.GetString("YouHaveRemovedSelectedLocalesReselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think you need to update....
        /// </summary>
        internal static string YouNeedToUpdate {
            get {
                return ResourceManager.GetString("YouNeedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your proxy not working....
        /// </summary>
        internal static string YourProxyNotWorking {
            get {
                return ResourceManager.GetString("YourProxyNotWorking", resourceCulture);
            }
        }
    }
}
